### ISSUE TITLE
Misspelled URL? https://github.com/google/double-conversion/archive/v3.1.5/double-converion-3.1.5.tar.gz

### ISSUE THREAD

**Issue by rubyFeedback** [google/double-conversion#132] opened 2020-05-06 22:53 UTC
Hey guys,

on BLFS here:

http://www.linuxfromscratch.org/blfs/view/cvs/general/double-conversion.html

I noticed this URL:

https://github.com/google/double-conversion/archive/v3.1.5/double-converion-3.1.5.tar.gz

At first it was a typo, but the URL works.

Has a "s" been forgotten e. g. "double-conversion" rather than "double-converion"?

Just mentioning in case that was some typo, the extracted directory extracts to "double-conversion" etc...

**Comment by floitsch** [comment] 2020-05-07 18:10
Interesting.
This seems to be a feature of github: any path to `https://github.com/google/double-conversion/archive/v3.1.5/*.tar.gz` will download `double-conversion-3.1.5.tar.gz`.

I think it's safe to just update the URL in BLFS.
If you have an account there, maybe file an issue?
If not, I can see if I can create an account and notify the owner of the package.

**Comment by floitsch** [comment] 2021-02-14 17:42
Has been fixed on BLFS

**Closed by floitsch** 2021-02-14 17:42 UTC

**Comment by Puma2511a** [comment] 2022-04-03 08:42
1. > ###  #`_**__*
Duplicate of #*_`
